name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.3
        with:
          node-version: '10.16.0'
          registry-url: https://registry.npmjs.org/
      - name: Build
        run: |
          rm -rf node_modules
          npm cache clean --force
          npm cache verify
          make all
      - name: Test
        run: make test
